version: 2
jobs:
  build:
    docker:
      - image: node:16.0.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      # run tests!
      - run: yarn netlify:deploy
